"""Add set column to Card model

Revision ID: 2f049a9ef72f
Revises: 0d3a195f26e0
Create Date: 2022-08-07 16:14:52.385022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f049a9ef72f'
down_revision = '0d3a195f26e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('set', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'set')
    # ### end Alembic commands ###
