"""Add owner_id in Card model as a foreign_key to the traders table

Revision ID: bc1f358481a2
Revises: 35290217e039
Create Date: 2022-08-07 14:53:29.729649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1f358481a2'
down_revision = '35290217e039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'card', 'trader', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'owner_id')
    # ### end Alembic commands ###
