"""Add foil column to Card model

Revision ID: f949fe218804
Revises: 2f049a9ef72f
Create Date: 2022-08-07 16:16:03.489286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f949fe218804'
down_revision = '2f049a9ef72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('foil', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'foil')
    # ### end Alembic commands ###
